
DROP TABLE IF EXISTS USERS;

CREATE TABLE IF NOT EXISTS USERS (
    id SERIAL PRIMARY KEY NOT NULL,
    username VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255),
    password VARCHAR(1024) NOT NULL UNIQUE,
    image VARCHAR(1024),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

SELECT *
FROM USERS;
