
DROP TABLE IF EXISTS COMMAND_DETAILS;
CREATE TABLE IF NOT EXISTS COMMAND_DETAILS (
    id SERIAL NOT NULL PRIMARY KEY,
    ref_command INT NOT NULL REFERENCES commands(id),
    ref_dish INT NOT NULL REFERENCES dishes(id),
    quantity INT NOT NULL,
    unit_price REAL NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);